namespace NaroCppCore.Occ.Xw
{
	public enum XwTypeOfVisual{
		Xw_TOV_STATICGRAY,
		Xw_TOV_GRAYSCALE,
		Xw_TOV_STATICCOLOR,
		Xw_TOV_PSEUDOCOLOR,
		Xw_TOV_TRUECOLOR,
		Xw_TOV_DIRECTCOLOR,
		Xw_TOV_DEFAULT,
		Xw_TOV_PREFERRED_PSEUDOCOLOR,
		Xw_TOV_PREFERRED_TRUECOLOR,
		Xw_TOV_PREFERRED_OVERLAY,
		Xw_TOV_OVERLAY,
	}
}
