//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Modeling {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PropertyDescriptorsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertyDescriptorsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Modeling.PropertyDescriptorsResources", typeof(PropertyDescriptorsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End angle.
        /// </summary>
        public static string ArcTab_EndAngle {
            get {
                return ResourceManager.GetString("ArcTab_EndAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal angle.
        /// </summary>
        public static string ArcTab_InternalAngle {
            get {
                return ResourceManager.GetString("ArcTab_InternalAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start angle.
        /// </summary>
        public static string ArcTab_StartAngle {
            get {
                return ResourceManager.GetString("ArcTab_StartAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string CircleRangeConstraintTab_Length {
            get {
                return ResourceManager.GetString("CircleRangeConstraintTab_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set circle range.
        /// </summary>
        public static string CircleRangeConstraintTabSetCircleRange {
            get {
                return ResourceManager.GetString("CircleRangeConstraintTabSetCircleRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius.
        /// </summary>
        public static string CircleTab_Range {
            get {
                return ResourceManager.GetString("CircleTab_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cone Height Constraint.
        /// </summary>
        public static string Cone_Height_Constraint {
            get {
                return ResourceManager.GetString("Cone_Height_Constraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cone Major Radius Constraint.
        /// </summary>
        public static string Cone_Major_Radius_Constraint {
            get {
                return ResourceManager.GetString("Cone_Major_Radius_Constraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cone Minor Radius Constraint.
        /// </summary>
        public static string Cone_Minor_Radius_Constraint {
            get {
                return ResourceManager.GetString("Cone_Minor_Radius_Constraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cylinder Height Constraint.
        /// </summary>
        public static string Cylinder_Height_Constraint {
            get {
                return ResourceManager.GetString("Cylinder_Height_Constraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cylinder Radius Constraint.
        /// </summary>
        public static string Cylinder_Radius_Constraint {
            get {
                return ResourceManager.GetString("Cylinder_Radius_Constraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set major radius.
        /// </summary>
        public static string EllipseTab_Set_major_radius {
            get {
                return ResourceManager.GetString("EllipseTab_Set_major_radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set minor radius.
        /// </summary>
        public static string EllipseTab_Set_minor_radius {
            get {
                return ResourceManager.GetString("EllipseTab_Set_minor_radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fillet2D.
        /// </summary>
        public static string Fillet2D {
            get {
                return ResourceManager.GetString("Fillet2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string HorizontalLineTab_Y {
            get {
                return ResourceManager.GetString("HorizontalLineTab_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Length Constraint.
        /// </summary>
        public static string Line_Length_Constraint {
            get {
                return ResourceManager.GetString("Line_Length_Constraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Radius.
        /// </summary>
        public static string Major_Radius {
            get {
                return ResourceManager.GetString("Major_Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor Radius.
        /// </summary>
        public static string Minor_Radius {
            get {
                return ResourceManager.GetString("Minor_Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius.
        /// </summary>
        public static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle Height Constraint.
        /// </summary>
        public static string Rectangle_Height_Constraint {
            get {
                return ResourceManager.GetString("Rectangle_Height_Constraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle Width Constraint.
        /// </summary>
        public static string Rectangle_Width_Constraint {
            get {
                return ResourceManager.GetString("Rectangle_Width_Constraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sphere Radius Constraint.
        /// </summary>
        public static string Sphere_Radius_Constraint {
            get {
                return ResourceManager.GetString("Sphere_Radius_Constraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arc.
        /// </summary>
        public static string TabTitleArc {
            get {
                return ResourceManager.GetString("TabTitleArc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box.
        /// </summary>
        public static string TabTitleBox {
            get {
                return ResourceManager.GetString("TabTitleBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        public static string TabTitleCircle {
            get {
                return ResourceManager.GetString("TabTitleCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ellipse.
        /// </summary>
        public static string TabTitleEllipse {
            get {
                return ResourceManager.GetString("TabTitleEllipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Line.
        /// </summary>
        public static string TabTitleHorizontalLine {
            get {
                return ResourceManager.GetString("TabTitleHorizontalLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string TabTitleLine {
            get {
                return ResourceManager.GetString("TabTitleLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear Pattern Tool.
        /// </summary>
        public static string TabTitleLinearPatternTool {
            get {
                return ResourceManager.GetString("TabTitleLinearPatternTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallogram.
        /// </summary>
        public static string TabTitleParallogram {
            get {
                return ResourceManager.GetString("TabTitleParallogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        public static string TabTitlePoint {
            get {
                return ResourceManager.GetString("TabTitlePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle.
        /// </summary>
        public static string TabTitleRectangle {
            get {
                return ResourceManager.GetString("TabTitleRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Line.
        /// </summary>
        public static string TabTitleVerticalLine {
            get {
                return ResourceManager.GetString("TabTitleVerticalLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle Range Constraint.
        /// </summary>
        public static string TitleTabCircleRangeConstraint {
            get {
                return ResourceManager.GetString("TitleTabCircleRangeConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cone.
        /// </summary>
        public static string TitleTabCone {
            get {
                return ResourceManager.GetString("TitleTabCone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string TitleTabCut {
            get {
                return ResourceManager.GetString("TitleTabCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cylinder.
        /// </summary>
        public static string TitleTabCylinder {
            get {
                return ResourceManager.GetString("TitleTabCylinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extrude.
        /// </summary>
        public static string TitleTabExtrude {
            get {
                return ResourceManager.GetString("TitleTabExtrude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fillet.
        /// </summary>
        public static string TitleTabFillet {
            get {
                return ResourceManager.GetString("TitleTabFillet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Length Constraint.
        /// </summary>
        public static string TitleTabLineLengthConstraint {
            get {
                return ResourceManager.GetString("TitleTabLineLengthConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        public static string TitleTabOffset {
            get {
                return ResourceManager.GetString("TitleTabOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle Height Constraint.
        /// </summary>
        public static string TitleTabRectangleHeightConstraint {
            get {
                return ResourceManager.GetString("TitleTabRectangleHeightConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle Width Constraint.
        /// </summary>
        public static string TitleTabRectangleWidthConstraint {
            get {
                return ResourceManager.GetString("TitleTabRectangleWidthConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revolve.
        /// </summary>
        public static string TitleTabRevolve {
            get {
                return ResourceManager.GetString("TitleTabRevolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sphere.
        /// </summary>
        public static string TitleTabSphere {
            get {
                return ResourceManager.GetString("TitleTabSphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torus.
        /// </summary>
        public static string TitleTabTorus {
            get {
                return ResourceManager.GetString("TitleTabTorus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torus Major Radius.
        /// </summary>
        public static string Torus_Major_Radius {
            get {
                return ResourceManager.GetString("Torus_Major_Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torus Minor Radius Constraint.
        /// </summary>
        public static string Torus_Minor_Radius_Constraint {
            get {
                return ResourceManager.GetString("Torus_Minor_Radius_Constraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string VerticalLineTab_X {
            get {
                return ResourceManager.GetString("VerticalLineTab_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
