namespace NaroCppCore.Occ.AIS
{
	public enum AISKindOfUnit{
		AIS_TOU_LENGTH,
		AIS_TOU_SURFACE,
		AIS_TOU_VOLUME,
		AIS_TOU_PLANE_ANGLE,
		AIS_TOU_SOLID_ANGLE,
		AIS_TOU_MASS,
		AIS_TOU_FORCE,
		AIS_TOU_TIME,
	}
}
