//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.PartModelling {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PartModelling.ModelingResources", typeof(ModelingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select face to be drafted.
        /// </summary>
        public static string AngleDraftStep1 {
            get {
                return ResourceManager.GetString("AngleDraftStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select reference plane for draft.
        /// </summary>
        public static string AngleDraftStep2 {
            get {
                return ResourceManager.GetString("AngleDraftStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft angle.
        /// </summary>
        public static string AngleDraftStep3 {
            get {
                return ResourceManager.GetString("AngleDraftStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arc radius.
        /// </summary>
        public static string ArcRSEStep1 {
            get {
                return ResourceManager.GetString("ArcRSEStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start point of arc.
        /// </summary>
        public static string ArcRSEStep2 {
            get {
                return ResourceManager.GetString("ArcRSEStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End point of arc.
        /// </summary>
        public static string ArcRSEStep3 {
            get {
                return ResourceManager.GetString("ArcRSEStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First point of arc.
        /// </summary>
        public static string ArcSERStep1 {
            get {
                return ResourceManager.GetString("ArcSERStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second point of arc.
        /// </summary>
        public static string ArcSERStep2 {
            get {
                return ResourceManager.GetString("ArcSERStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arc radius.
        /// </summary>
        public static string ArcSERStep3 {
            get {
                return ResourceManager.GetString("ArcSERStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select shape to remove from.
        /// </summary>
        public static string BooleanCutStep1 {
            get {
                return ResourceManager.GetString("BooleanCutStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select shape to remove with.
        /// </summary>
        public static string BooleanCutStep2 {
            get {
                return ResourceManager.GetString("BooleanCutStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select first shape to fuse .
        /// </summary>
        public static string BooleanFuseStep1 {
            get {
                return ResourceManager.GetString("BooleanFuseStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select second shape to fuse with.
        /// </summary>
        public static string BooleanFuseStep2 {
            get {
                return ResourceManager.GetString("BooleanFuseStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select first shape.
        /// </summary>
        public static string BooleanIntersectStep1 {
            get {
                return ResourceManager.GetString("BooleanIntersectStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select shape which intersects first shape.
        /// </summary>
        public static string BooleanIntersectStep2 {
            get {
                return ResourceManager.GetString("BooleanIntersectStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Box point.
        /// </summary>
        public static string BoxStep1 {
            get {
                return ResourceManager.GetString("BoxStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Box point.
        /// </summary>
        public static string BoxStep2 {
            get {
                return ResourceManager.GetString("BoxStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box height.
        /// </summary>
        public static string BoxStep3 {
            get {
                return ResourceManager.GetString("BoxStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle center.
        /// </summary>
        public static string CircleStep1 {
            get {
                return ResourceManager.GetString("CircleStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle radius.
        /// </summary>
        public static string CircleStep2 {
            get {
                return ResourceManager.GetString("CircleStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cone center.
        /// </summary>
        public static string ConeStep1 {
            get {
                return ResourceManager.GetString("ConeStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base radius.
        /// </summary>
        public static string ConeStep2 {
            get {
                return ResourceManager.GetString("ConeStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cone height.
        /// </summary>
        public static string ConeStep3 {
            get {
                return ResourceManager.GetString("ConeStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number format.
        /// </summary>
        public static string ConstraintShapeDialog_Invalid_number_format {
            get {
                return ResourceManager.GetString("ConstraintShapeDialog_Invalid_number_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cylinder center.
        /// </summary>
        public static string CylinderStep1 {
            get {
                return ResourceManager.GetString("CylinderStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cylinder base radius.
        /// </summary>
        public static string CylinderStep2 {
            get {
                return ResourceManager.GetString("CylinderStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cylinder height.
        /// </summary>
        public static string CylinderStep3 {
            get {
                return ResourceManager.GetString("CylinderStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XOY set as default sketch plane.
        /// </summary>
        public static string DefaultSketchPlane {
            get {
                return ResourceManager.GetString("DefaultSketchPlane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First ellipse point.
        /// </summary>
        public static string EllipseStep1 {
            get {
                return ResourceManager.GetString("EllipseStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second ellipse point.
        /// </summary>
        public static string EllipseStep2 {
            get {
                return ResourceManager.GetString("EllipseStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third ellipse point.
        /// </summary>
        public static string EllipseStep3 {
            get {
                return ResourceManager.GetString("EllipseStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception on Mouse Click.
        /// </summary>
        public static string Exception_On_Mouse_Click {
            get {
                return ResourceManager.GetString("Exception_On_Mouse_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select face to extrude.
        /// </summary>
        public static string ExtrudeStep1 {
            get {
                return ResourceManager.GetString("ExtrudeStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extrusion height.
        /// </summary>
        public static string ExtrudeStep2 {
            get {
                return ResourceManager.GetString("ExtrudeStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found on disk.
        /// </summary>
        public static string File_not_found_on_disk {
            get {
                return ResourceManager.GetString("File_not_found_on_disk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the first edge.
        /// </summary>
        public static string FilletStep1 {
            get {
                return ResourceManager.GetString("FilletStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the second edge.
        /// </summary>
        public static string FilletStep2 {
            get {
                return ResourceManager.GetString("FilletStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file to load.
        /// </summary>
        public static string Invalid_file_to_load {
            get {
                return ResourceManager.GetString("Invalid_file_to_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select line to be constrained.
        /// </summary>
        public static string LineLengthConstraintStep1 {
            get {
                return ResourceManager.GetString("LineLengthConstraintStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed length value.
        /// </summary>
        public static string LineLengthConstraintStep2 {
            get {
                return ResourceManager.GetString("LineLengthConstraintStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First point of line.
        /// </summary>
        public static string LineStep1 {
            get {
                return ResourceManager.GetString("LineStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second point of line.
        /// </summary>
        public static string LineStep2 {
            get {
                return ResourceManager.GetString("LineStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select shape to mirror.
        /// </summary>
        public static string MirrorLineStep1 {
            get {
                return ResourceManager.GetString("MirrorLineStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select mirror line.
        /// </summary>
        public static string MirrorLineStep2 {
            get {
                return ResourceManager.GetString("MirrorLineStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select shape to mirror.
        /// </summary>
        public static string MirrorPlaneStep1 {
            get {
                return ResourceManager.GetString("MirrorPlaneStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select mirror plane.
        /// </summary>
        public static string MirrorPlaneStep2 {
            get {
                return ResourceManager.GetString("MirrorPlaneStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select shape to mirror.
        /// </summary>
        public static string MirrorPointStep1 {
            get {
                return ResourceManager.GetString("MirrorPointStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select mirror point.
        /// </summary>
        public static string MirrorPointStep2 {
            get {
                return ResourceManager.GetString("MirrorPointStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the normal plane.
        /// </summary>
        public static string NormalLineStep2 {
            get {
                return ResourceManager.GetString("NormalLineStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select 2D closed shape to offset.
        /// </summary>
        public static string OffsetStep1 {
            get {
                return ResourceManager.GetString("OffsetStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset distance.
        /// </summary>
        public static string OffsetStep2 {
            get {
                return ResourceManager.GetString("OffsetStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the parallel plane.
        /// </summary>
        public static string ParllelLineStep2 {
            get {
                return ResourceManager.GetString("ParllelLineStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select pattern reference.
        /// </summary>
        public static string PatternSte2 {
            get {
                return ResourceManager.GetString("PatternSte2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select pattern shape.
        /// </summary>
        public static string PatternStep1 {
            get {
                return ResourceManager.GetString("PatternStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipe base.
        /// </summary>
        public static string PipeStep1 {
            get {
                return ResourceManager.GetString("PipeStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipe direction.
        /// </summary>
        public static string PipeStep2 {
            get {
                return ResourceManager.GetString("PipeStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point coordinate.
        /// </summary>
        public static string PointStep1 {
            get {
                return ResourceManager.GetString("PointStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select circle to be constrained.
        /// </summary>
        public static string RadiusConstraintStep1 {
            get {
                return ResourceManager.GetString("RadiusConstraintStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed radius value.
        /// </summary>
        public static string RadiusConstraintStep2 {
            get {
                return ResourceManager.GetString("RadiusConstraintStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select rectangle who&apos;s height to be constrained.
        /// </summary>
        public static string RectangleHeightConstraintStep1 {
            get {
                return ResourceManager.GetString("RectangleHeightConstraintStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed height value.
        /// </summary>
        public static string RectangleHeightConstraintStep2 {
            get {
                return ResourceManager.GetString("RectangleHeightConstraintStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First rectangle point.
        /// </summary>
        public static string RectangleStep1 {
            get {
                return ResourceManager.GetString("RectangleStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First rectangle point and direction.
        /// </summary>
        public static string RectangleStep1Direction {
            get {
                return ResourceManager.GetString("RectangleStep1Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second rectangle point.
        /// </summary>
        public static string RectangleStep2 {
            get {
                return ResourceManager.GetString("RectangleStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third rectangle point.
        /// </summary>
        public static string RectangleStep3 {
            get {
                return ResourceManager.GetString("RectangleStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select rectangle who&apos;s width to be constrained.
        /// </summary>
        public static string RectangleWidthConstraintStep1 {
            get {
                return ResourceManager.GetString("RectangleWidthConstraintStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed width value.
        /// </summary>
        public static string RectangleWidthConstraintStep2 {
            get {
                return ResourceManager.GetString("RectangleWidthConstraintStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select shape to revolve.
        /// </summary>
        public static string RevolveStep1 {
            get {
                return ResourceManager.GetString("RevolveStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select reference shape.
        /// </summary>
        public static string RevolveStep2 {
            get {
                return ResourceManager.GetString("RevolveStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sew first shape.
        /// </summary>
        public static string SewStep1 {
            get {
                return ResourceManager.GetString("SewStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sew second shape.
        /// </summary>
        public static string SewStep2 {
            get {
                return ResourceManager.GetString("SewStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape mapping not found .
        /// </summary>
        public static string Shape_mapping_not_found {
            get {
                return ResourceManager.GetString("Shape_mapping_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sketch plane selected.
        /// </summary>
        public static string SketchPlaneSelected {
            get {
                return ResourceManager.GetString("SketchPlaneSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sphere center.
        /// </summary>
        public static string SphereStep1 {
            get {
                return ResourceManager.GetString("SphereStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sphere radius.
        /// </summary>
        public static string SphereStep2 {
            get {
                return ResourceManager.GetString("SphereStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First point of spline.
        /// </summary>
        public static string SplineStep1 {
            get {
                return ResourceManager.GetString("SplineStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next point of spline.
        /// </summary>
        public static string SplineStep2 {
            get {
                return ResourceManager.GetString("SplineStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a sketch plane.
        /// </summary>
        public static string StartSketch {
            get {
                return ResourceManager.GetString("StartSketch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center location.
        /// </summary>
        public static string TorusStep1 {
            get {
                return ResourceManager.GetString("TorusStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal radius.
        /// </summary>
        public static string TorusStep2 {
            get {
                return ResourceManager.GetString("TorusStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External radius.
        /// </summary>
        public static string TorusStep3 {
            get {
                return ResourceManager.GetString("TorusStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape to translate.
        /// </summary>
        public static string TranslateStep1 {
            get {
                return ResourceManager.GetString("TranslateStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Point.
        /// </summary>
        public static string TranslateStep2 {
            get {
                return ResourceManager.GetString("TranslateStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation Point.
        /// </summary>
        public static string TranslateStep3 {
            get {
                return ResourceManager.GetString("TranslateStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an edge to trim.
        /// </summary>
        public static string Trim {
            get {
                return ResourceManager.GetString("Trim", resourceCulture);
            }
        }
    }
}
