//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.CompositeUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.CompositeUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command adapter has already been bound to a command..
        /// </summary>
        internal static string AdapterAlreadyBoundToACommand {
            get {
                return ResourceManager.GetString("AdapterAlreadyBoundToACommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The adapter has not been previously bound to the command..
        /// </summary>
        internal static string AdapterNotBoundToGivenCommand {
            get {
                return ResourceManager.GetString("AdapterNotBoundToGivenCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddServices() method called for Module {0}..
        /// </summary>
        internal static string AddServicesCalled {
            get {
                return ResourceManager.GetString("AddServicesCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This code is required by the smart part informations..
        /// </summary>
        internal static string AutogeneratedCodeWarning {
            get {
                return ResourceManager.GetString("AutogeneratedCodeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception thrown in a background subscriber was not handled. The exception was {0}..
        /// </summary>
        internal static string BackgroundSubscriberException {
            get {
                return ResourceManager.GetString("BackgroundSubscriberException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A WorkItem cannot be added to itself..
        /// </summary>
        internal static string CannotAddWorkItemToItself {
            get {
                return ResourceManager.GetString("CannotAddWorkItemToItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified event {0} was not found in the publisher..
        /// </summary>
        internal static string CannotFindPublishedEvent {
            get {
                return ResourceManager.GetString("CannotFindPublishedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Command {0} cannot get an adapter for the type &quot;{1}&quot;.
        /// </summary>
        internal static string CannotGetCommandAdapter {
            get {
                return ResourceManager.GetString("CannotGetCommandAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Command &quot;{0}&quot; does not have access to the IAdapterMapService to perform the AddInvoker operation..
        /// </summary>
        internal static string CannotGetMapService {
            get {
                return ResourceManager.GetString("CannotGetMapService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the state with id {0} from the storage..
        /// </summary>
        internal static string CannotLoadState {
            get {
                return ResourceManager.GetString("CannotLoadState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription {0}.{1} is static and is not supported..
        /// </summary>
        internal static string CannotRegisterStaticSubscriptionMethods {
            get {
                return ResourceManager.GetString("CannotRegisterStaticSubscriptionMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving the state with id {0} to the storage..
        /// </summary>
        internal static string CannotSaveState {
            get {
                return ResourceManager.GetString("CannotSaveState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot unregister site that was registered in parent: {0}.
        /// </summary>
        internal static string CannotUnregisterSiteRegisteredWithParent {
            get {
                return ResourceManager.GetString("CannotUnregisterSiteRegisteredWithParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding command handler on {0} for command &apos;{1}&apos;.
        /// </summary>
        internal static string CommandInjectionBuildUp {
            get {
                return ResourceManager.GetString("CommandInjectionBuildUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing command handler from {0} for command &apos;{1}&apos;.
        /// </summary>
        internal static string CommandInjectionTearDown {
            get {
                return ResourceManager.GetString("CommandInjectionTearDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property marked as configuration property is not valid as its type {0} does not inherit from ApplicationSettingsBase..
        /// </summary>
        internal static string ConfigurationAttributeOnValueWithIncompatibleType {
            get {
                return ResourceManager.GetString("ConfigurationAttributeOnValueWithIncompatibleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings must be user-scoped in order to use the selected provider. .
        /// </summary>
        internal static string ConfigurationProviderMustBeUserScoped {
            get {
                return ResourceManager.GetString("ConfigurationProviderMustBeUserScoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This provider only supports settings classes defined in assemblies deployed locally..
        /// </summary>
        internal static string ConfigurationProviderNotSupportLocation {
            get {
                return ResourceManager.GetString("ConfigurationProviderNotSupportLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No default profile has been specified..
        /// </summary>
        internal static string DefaultProfileNotSpecified {
            get {
                return ResourceManager.GetString("DefaultProfileNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add dependency for unknown module &apos;{0}&apos;; call AddModule() before AddDependency().
        /// </summary>
        internal static string DependencyForUnknownModule {
            get {
                return ResourceManager.GetString("DependencyForUnknownModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A module declared a dependency on another module which is not declared to be loaded. Missing module(s): {0}.
        /// </summary>
        internal static string DependencyOnMissingModule {
            get {
                return ResourceManager.GetString("DependencyOnMissingModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dictionary is readonly and can not be modified..
        /// </summary>
        internal static string DictionaryIsReadOnly {
            get {
                return ResourceManager.GetString("DictionaryIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A duplicated module with name {0} has been found by the loader..
        /// </summary>
        internal static string DuplicatedModule {
            get {
                return ResourceManager.GetString("DuplicatedModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object with this ID already exists: {0}..
        /// </summary>
        internal static string DuplicateID {
            get {
                return ResourceManager.GetString("DuplicateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service of this type already exists: {0}..
        /// </summary>
        internal static string DuplicateService {
            get {
                return ResourceManager.GetString("DuplicateService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A UI extension site with this name already exists: {0}.
        /// </summary>
        internal static string DuplicateUIExtensionSite {
            get {
                return ResourceManager.GetString("DuplicateUIExtensionSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while enumerating the modules using the {0} enumerator..
        /// </summary>
        internal static string ErrorEnumeratingModules {
            get {
                return ResourceManager.GetString("ErrorEnumeratingModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while reading the solution profile {0}..
        /// </summary>
        internal static string ErrorReadingProfile {
            get {
                return ResourceManager.GetString("ErrorReadingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoker is not of type {0}.
        /// </summary>
        internal static string EventCommandAdapterInvokerNotType {
            get {
                return ResourceManager.GetString("EventCommandAdapterInvokerNotType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event {0} on the invoker {1} is not present..
        /// </summary>
        internal static string EventNotPresentOnInvoker {
            get {
                return ResourceManager.GetString("EventNotPresentOnInvoker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more exceptions occurred while firing the topic &apos;{0}&apos;.
        /// </summary>
        internal static string EventTopicFireException {
            get {
                return ResourceManager.GetString("EventTopicFireException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventTopic {0} fire completed..
        /// </summary>
        internal static string EventTopicTraceFireCompleted {
            get {
                return ResourceManager.GetString("EventTopicTraceFireCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptions occurred while firing the EventTopic {0}..
        /// </summary>
        internal static string EventTopicTraceFireExceptions {
            get {
                return ResourceManager.GetString("EventTopicTraceFireExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firing EventTopic {0}.
        /// </summary>
        internal static string EventTopicTraceFireStarted {
            get {
                return ResourceManager.GetString("EventTopicTraceFireStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication for the EventTopic {0} was added for the event {1} on the type {2}..
        /// </summary>
        internal static string EventTopicTracePublicationAdded {
            get {
                return ResourceManager.GetString("EventTopicTracePublicationAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication removed from EventTopic {0} for the event {1} on the type {2}.
        /// </summary>
        internal static string EventTopicTracePublicationRemoved {
            get {
                return ResourceManager.GetString("EventTopicTracePublicationRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription for EventTopic {0} added for the method {1} on the type {2}.
        /// </summary>
        internal static string EventTopicTraceSubscriptionAdded {
            get {
                return ResourceManager.GetString("EventTopicTraceSubscriptionAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription on EventTopic {0} removed for the method {1} on the type {2}.
        /// </summary>
        internal static string EventTopicTraceSubscriptionRemoved {
            get {
                return ResourceManager.GetString("EventTopicTraceSubscriptionRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension site does not exist: {0}.
        /// </summary>
        internal static string ExtensionSiteDoesNotExist {
            get {
                return ResourceManager.GetString("ExtensionSiteDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load module from assembly {0}. Error was:
        ///{1}.
        /// </summary>
        internal static string FailedToLoadModule {
            get {
                return ResourceManager.GetString("FailedToLoadModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The adapter type is not a ICommandAdapter..
        /// </summary>
        internal static string InvalidAdapter {
            get {
                return ResourceManager.GetString("InvalidAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an error in the XML document. &lt;{0} xmlns=&apos;{1}&apos;&gt; was not expected..
        /// </summary>
        internal static string InvalidCatalogXml {
            get {
                return ResourceManager.GetString("InvalidCatalogXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration section {0} must be of type {1}..
        /// </summary>
        internal static string InvalidConfigurationSectionType {
            get {
                return ResourceManager.GetString("InvalidConfigurationSectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UseCryptography setting must be set to a valid boolean value..
        /// </summary>
        internal static string InvalidCryptographyValue {
            get {
                return ResourceManager.GetString("InvalidCryptographyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the argument {0} provided for the enumeration {1} is invalid..
        /// </summary>
        internal static string InvalidEnumValue {
            get {
                return ResourceManager.GetString("InvalidEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog file path cannot be empty or null, and must be a local file under the application folder..
        /// </summary>
        internal static string InvalidFileCatalogFilePath {
            get {
                return ResourceManager.GetString("InvalidFileCatalogFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open an isolated store with scope {0}. Check the IsolatedStorageFile documentation for the valid combination of values..
        /// </summary>
        internal static string InvalidIsolatedStorageStatePersistanceParsedScope {
            get {
                return ResourceManager.GetString("InvalidIsolatedStorageStatePersistanceParsedScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope value {0} is invalid. {1} does not exist in the IsolatedStorageScope enumeration..
        /// </summary>
        internal static string InvalidIsolatedStorageStatePersistanceScope {
            get {
                return ResourceManager.GetString("InvalidIsolatedStorageStatePersistanceScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for the PublicationScope is invalid..
        /// </summary>
        internal static string InvalidPublicationScope {
            get {
                return ResourceManager.GetString("InvalidPublicationScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication event {0}.{1} must have a delegate type compatible with EventHandler or EventHandler&lt;T&gt;..
        /// </summary>
        internal static string InvalidPublicationSignature {
            get {
                return ResourceManager.GetString("InvalidPublicationSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog file path {0} is not a local file under the application folder {1}..
        /// </summary>
        internal static string InvalidSolutionProfilePath {
            get {
                return ResourceManager.GetString("InvalidSolutionProfilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an error in the XML document. &lt;{0} xmlns=&apos;{1}&apos;&gt; was not expected..
        /// </summary>
        internal static string InvalidSolutionProfileXml {
            get {
                return ResourceManager.GetString("InvalidSolutionProfileXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State stream from storage is invalid..
        /// </summary>
        internal static string InvalidStateStream {
            get {
                return ResourceManager.GetString("InvalidStateStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription method {0}.{1} must have a signature receiving an object and an EventArgs parameter (EventHandler or EventHandler&lt;T&gt; delegates signature)..
        /// </summary>
        internal static string InvalidSubscriptionSignature {
            get {
                return ResourceManager.GetString("InvalidSubscriptionSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module {0} added to the container..
        /// </summary>
        internal static string LogModuleAdded {
            get {
                return ResourceManager.GetString("LogModuleAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded assembly file {0} for Module..
        /// </summary>
        internal static string LogModuleAssemblyLoaded {
            get {
                return ResourceManager.GetString("LogModuleAssemblyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly file {0} was not found..
        /// </summary>
        internal static string ModuleNotFound {
            get {
                return ResourceManager.GetString("ModuleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly path {0} does not fall under the current application root..
        /// </summary>
        internal static string ModulePathNotUnderRoot {
            get {
                return ResourceManager.GetString("ModulePathNotUnderRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load() method called for Module {0}..
        /// </summary>
        internal static string ModuleStartCalled {
            get {
                return ResourceManager.GetString("ModuleStartCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No UIElementAdapterFactory register for type {0}..
        /// </summary>
        internal static string NoRegisteredUIElementFactory {
            get {
                return ResourceManager.GetString("NoRegisteredUIElementFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing WorkItems is not permitted. Use WorkItem.Terminate or WorkItem.Dispose to clean up a WorkItem..
        /// </summary>
        internal static string NoRemoveWorkItemFromManagedObjectCollection {
            get {
                return ResourceManager.GetString("NoRemoveWorkItemFromManagedObjectCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service implementation {0} returned a null reader for the catalog..
        /// </summary>
        internal static string NullReaderReturned {
            get {
                return ResourceManager.GetString("NullReaderReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ModuleEnumerator implementation {0} returned a null reader for the catalog..
        /// </summary>
        internal static string NullSolutionProfileReaderReturned {
            get {
                return ResourceManager.GetString("NullSolutionProfileReaderReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add more than one instance of the same publisher to one topic..
        /// </summary>
        internal static string OnlyOnePublicationIsAllowed {
            get {
                return ResourceManager.GetString("OnlyOnePublicationIsAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile {0} was not found in the catalog..
        /// </summary>
        internal static string ProfileNotFound {
            get {
                return ResourceManager.GetString("ProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile {0} was not found in the catalog..
        /// </summary>
        internal static string ProfileNotFoundInCatalog {
            get {
                return ResourceManager.GetString("ProfileNotFoundInCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while reading the profile..
        /// </summary>
        internal static string ReadProfileException {
            get {
                return ResourceManager.GetString("ReadProfileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ModuleLoaderService cannot initialize the module because some of their dependencies are not present. Make sure to deploy all the assemblies needed to execute the module..
        /// </summary>
        internal static string ReferencedAssemblyNotFound {
            get {
                return ResourceManager.GetString("ReferencedAssemblyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing Commands from WorkItem is not permitted. An attempt was made to remove the command {0}..
        /// </summary>
        internal static string RemoveCommandFromWorkItemIsNotPermitted {
            get {
                return ResourceManager.GetString("RemoveCommandFromWorkItemIsNotPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing EventTopic from WorkItem is not permitted. An attempt was made to remove the EventTopic {0}..
        /// </summary>
        internal static string RemoveEventTopicFromWorkItemIsNotPermitted {
            get {
                return ResourceManager.GetString("RemoveEventTopicFromWorkItemIsNotPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {1} added for Module {0}..
        /// </summary>
        internal static string ServiceAdded {
            get {
                return ResourceManager.GetString("ServiceAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {1} will be added on demand for Module {0}..
        /// </summary>
        internal static string ServiceAddedOnDemand {
            get {
                return ResourceManager.GetString("ServiceAddedOnDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0}, required for component {1} is not available in the current context..
        /// </summary>
        internal static string ServiceMissingExceptionMessage {
            get {
                return ResourceManager.GetString("ServiceMissingExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} is not available in the current context..
        /// </summary>
        internal static string ServiceMissingExceptionSimpleMessage {
            get {
                return ResourceManager.GetString("ServiceMissingExceptionSimpleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implement ISmartPartInfoProvider in the containing smart part. Required in order for contained smart part infos to work..
        /// </summary>
        internal static string SmartPartMustImplementISmartPartInfoProvider {
            get {
                return ResourceManager.GetString("SmartPartMustImplementISmartPartInfoProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The smartpart is not present in the workspace..
        /// </summary>
        internal static string SmartPartNotInWorkspace {
            get {
                return ResourceManager.GetString("SmartPartNotInWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog file at location {0} could not be found..
        /// </summary>
        internal static string SolutionProfileNotFound {
            get {
                return ResourceManager.GetString("SolutionProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no state persisted with the given id {0}..
        /// </summary>
        internal static string StateDoesNotExist {
            get {
                return ResourceManager.GetString("StateDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static command handler &quot;{0}&quot; is not supported..
        /// </summary>
        internal static string StaticCommandHandlerNotSupported {
            get {
                return ResourceManager.GetString("StaticCommandHandlerNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static command publisher &quot;{0}&quot; is not supported..
        /// </summary>
        internal static string StaticCommandPublisherNotSupported {
            get {
                return ResourceManager.GetString("StaticCommandPublisherNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering static event {0} as topic publication is not allowed..
        /// </summary>
        internal static string StaticPublisherNotAllowed {
            get {
                return ResourceManager.GetString("StaticPublisherNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided String argument {0} must not be empty..
        /// </summary>
        internal static string StringCannotBeEmpty {
            get {
                return ResourceManager.GetString("StringCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified method handler {0} is not present or accessible on the subscriber type {1}..
        /// </summary>
        internal static string SubscriberHandlerNotFound {
            get {
                return ResourceManager.GetString("SubscriberHandlerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Command {0} has been executed..
        /// </summary>
        internal static string TraceCommandExecuted {
            get {
                return ResourceManager.GetString("TraceCommandExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command status for command {0} has changed to {1}..
        /// </summary>
        internal static string TraceCommandStatusChanged {
            get {
                return ResourceManager.GetString("TraceCommandStatusChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state with ID {0} has changed. The changed value was {1}..
        /// </summary>
        internal static string TraceStateChangedMessage {
            get {
                return ResourceManager.GetString("TraceStateChangedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The work item {0} has been run..
        /// </summary>
        internal static string TraceWorkItemRun {
            get {
                return ResourceManager.GetString("TraceWorkItemRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkItem {0} Run method has started..
        /// </summary>
        internal static string TraceWorkItemRunStarted {
            get {
                return ResourceManager.GetString("TraceWorkItemRunStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The work item {0} is Activating..
        /// </summary>
        internal static string TraceWorkItemStatusActivating {
            get {
                return ResourceManager.GetString("TraceWorkItemStatusActivating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The work item {0} is Activated..
        /// </summary>
        internal static string TraceWorkItemStatusChangedToActivated {
            get {
                return ResourceManager.GetString("TraceWorkItemStatusChangedToActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The work item {0} is Deactivated..
        /// </summary>
        internal static string TraceWorkItemStatusChangedToDeactivated {
            get {
                return ResourceManager.GetString("TraceWorkItemStatusChangedToDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The work item {0} is Disposed..
        /// </summary>
        internal static string TraceWorkItemStatusChangedToDisposed {
            get {
                return ResourceManager.GetString("TraceWorkItemStatusChangedToDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The work item {0} is Initialized..
        /// </summary>
        internal static string TraceWorkItemStatusChangedToInitialized {
            get {
                return ResourceManager.GetString("TraceWorkItemStatusChangedToInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The work item {0} is Terminated..
        /// </summary>
        internal static string TraceWorkItemStatusChangedToTerminated {
            get {
                return ResourceManager.GetString("TraceWorkItemStatusChangedToTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The work item {0} is Deactivating..
        /// </summary>
        internal static string TraceWorkItemStatusDeactivating {
            get {
                return ResourceManager.GetString("TraceWorkItemStatusDeactivating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The work item {0} is Terminating..
        /// </summary>
        internal static string TraceWorkItemStatusTerminating {
            get {
                return ResourceManager.GetString("TraceWorkItemStatusTerminating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided type {0} is not compatible with {1}..
        /// </summary>
        internal static string TypeNotCompatible {
            get {
                return ResourceManager.GetString("TypeNotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI element must be a {0}.
        /// </summary>
        internal static string UIElementNotCorrectType {
            get {
                return ResourceManager.GetString("UIElementNotCorrectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart part type {0} is not supported. Expected {1} or a compatible type..
        /// </summary>
        internal static string UnsupportedSmartPartType {
            get {
                return ResourceManager.GetString("UnsupportedSmartPartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The visualizer has already been initialized..
        /// </summary>
        internal static string VisualizerAlreadyInitialized {
            get {
                return ResourceManager.GetString("VisualizerAlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizer type must implement IVisualizer..
        /// </summary>
        internal static string VisualizerMustImplementIVisualizer {
            get {
                return ResourceManager.GetString("VisualizerMustImplementIVisualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not modify this method, changes will be lost upon regeneration by the designer..
        /// </summary>
        internal static string WorkItemDesignerCodeWarning {
            get {
                return ResourceManager.GetString("WorkItemDesignerCodeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized WorkItem extension {0} with WorkItem {1}..
        /// </summary>
        internal static string WorkItemExtensionInitialized {
            get {
                return ResourceManager.GetString("WorkItemExtensionInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered WorkItem extension type {0} for WorkItem type {1}..
        /// </summary>
        internal static string WorkItemExtensionRegistered {
            get {
                return ResourceManager.GetString("WorkItemExtensionRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered WorkItem extension type {0} for root WorkItem..
        /// </summary>
        internal static string WorkItemExtensionRootRegistered {
            get {
                return ResourceManager.GetString("WorkItemExtensionRootRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WorkItem Extension type {0} is already registered for WorkItem type {1}..
        /// </summary>
        internal static string WorkItemExtensionTypeAlreadyRegistered {
            get {
                return ResourceManager.GetString("WorkItemExtensionTypeAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkItem has already been disposed or terminated..
        /// </summary>
        internal static string WorkItemTerminated {
            get {
                return ResourceManager.GetString("WorkItemTerminated", resourceCulture);
            }
        }
    }
}
