//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add Business Module" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v90/MS.VSIPCC.v90/ms.practices.scsf.2008apr/SCSF/html/02-08-060-Add_Business_Module_Next_Steps.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace Naro.Sketcher.Constants
{
    /// <summary>
    /// Constants for command names.
    /// </summary>
    public class CommandNames : Naro.Infrastructure.Interface.Constants.CommandNames
    {
        public const string Cursor = "Cursor";

        public const string SketcherFitAll = "SketcherFitAll";
        public const string SketcherZoomWindow = "SketcherZoomWindow";
        public const string SketcherDynamicZooming = "SketcherDynamicZooming";
        public const string SketcherDynamicPanning = "SketcherDynamicPanning";
        public const string SketcherGlobalPanning = "SketcherGlobalPanning";

        public const string SketcherGridLines = "SketcherGridLines";
        public const string SketcherGridPoints = "SketcherGridPoints";
        public const string SketcherCircularGrid = "SketcherCircularGrid";
        public const string SketcherCircularGridPoints = "SketcherCircularGridPoints";
        public const string SketcherEditGrid = "SketcherEditGrid";
        public const string SketcherEraseGrid = "SketcherEraseGrid";

        // Drawing commands
        public const string SketcherDrawRectangle = "SketcherDrawRectangle";
        public const string SketcherDrawLine = "SketcherDrawLine";
        public const string SketcherDrawCircle = "SketcherDrawCircle";
    }
}

