//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add Business Module" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v90/MS.VSIPCC.v90/ms.practices.scsf.2008apr/SCSF/html/02-08-060-Add_Business_Module_Next_Steps.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace Naro.Sketcher.Constants
{
    /// <summary>
    /// Constants for event topic names.
    /// </summary>
    public class EventTopicNames : Naro.Infrastructure.Interface.Constants.EventTopicNames
    {
        public const string SketcherRepaintView = "SketcherRepaintView";
        public const string SketcherResizeView = "SketcherResizeView";
        public const string SketcherMouseDownEvent = "SketcherMouseDownEvent";
        public const string SketcherMouseUpEvent = "SketcherMouseUpEvent";
        public const string SketcherMouseMoveEvent = "SketcherMouseMoveEvent";
    }
}
